"""
Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""
import math

def get_triangle_number(n):
    return n * (n + 1) / 2

def is_pentagonal(number):
    x = math.sqrt(1 + 24 * number)
    intercept = 1.0 * (1 + x) / 6
    return intercept == int(intercept)
    
def is_hexagonal(number):
    x = math.sqrt(1 + 8 * number)
    intercept = 1.0 * (1 + x) / 4
    return intercept == int(intercept)
    
if __name__ == "__main__":
    i = 286
    while True:
        number = get_triangle_number(i)
        if is_pentagonal(number) and is_hexagonal(number):
            print number
            break
        i += 1